#!/bin/bash

# WARNING: This has a LIMIT of 32 characters for now!
# If your URL is longer you should use an URL shortener
# Caused by https://github.com/vivien/i3blocks/blob/01a4f4a9ca1e3d0b3c95d1d62000ad8506bdff1a/include/block.h#L50
# Example: https://goo.gl/
#FEED_URL="${BLOCK_INSTANCE:-https://www.archlinux.org/feeds/news/}"
#FEED_URL="${BLOCK_INSTANCE:-http://it.ign.com/feed.xml}"
#FEED_URL="${BLOCK_INSTANCE:-https://www.focus.it/rss/tecnologia.rss}"

ARR_URL=("http://it.ign.com/feed.xml" "https://www.archlinux.org/feeds/news/")

NUM=`cat numFeed.txt`
ARR_LEN=${#ARR_URL[@]}

if ((NUM >= ARR_LEN))
then
	NUM=0
	echo NUM > numFeed.txt
fi

FEED_URL="${BLOCK_INSTANCE:-${ARR_URL[NUM]}}" #echo ${ARR_URL[NUM]}
#echo $FEED_URL

if [[ "${FEED_URL}" = "" ]]; then
  exit
fi

# Follows redirects!
FEED_CONTENT=$(curl ${FEED_URL} -s -L)
FEED_TITLE=$(echo "${FEED_CONTENT}" | grep -v "xmlns:atom" | grep -o '<title>.*</title>' | head -n 1 | sed 's/\(<title>\|<\/title>\)//g')
FEED_LINK=$(echo "${FEED_CONTENT}"  | grep -v "xmlns:atom" | grep -o '<link>.*</link>' | head -n 1 | sed 's/\(<link>\|<\/link>\)//g')

if [[ "${FEED_TITLE}" = *404* ]]; then
  echo "${FEED_URL}"
  echo "${FEED_URL}"
  echo ""
  exit 33
fi

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xdg-open "${FEED_LINK}"
fi

echo "RSS: ${FEED_TITLE}"
#echo "${FEED_TITLE}"
#echo ""

let 'NUM=NUM+1'
echo $NUM > numFeed.txt
